name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: download
        run: |
          wget -O download.zip -P ./downloads/ https://huggingface.co/VideoCrafter/Image2Video-512/tree/main

      - name: split
        run: |
          split -b 2G ./downloads/download.zip split_file
      
      - name: upload
        run: |
          curl -fsSL git.io/file-transfer | sh 
          ./transfer cow --no-progress ./downloads

#      - name: upload
#        run: |
#          curl -fsSL git.io/file-transfer | sh
#          ./transfer wet --no-progress ./downloads/ 2>&1 | tee anon.log
#          echo "::warning file=anonfiles.com::$(cat anon.log | grep https)"
#          echo "::set-output name=url::$(cat anon.log | grep https | cut -f3 -d" ")"
#
#      - name: set up go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.18
#
#      - name: upload local
#        run: |
#          go run main.go
